# ------ Resssources ------ 
Percent_memory: 0.5
threads : 8 # single task nb threads
# ------ Path to data folder ------ 
data: /mnt/gpfs/seb/Project/Metahood/Test/Data  
# ------ Assembly parameters ------ 
assembly: 
  assembler: megahit
  per_sample: [sample*]
  groups: 
      AD1:
        [*]
      AD2:
        [sample1]
# ------ Annotation parameters ------ 
annotation:
  CARD:
    db: [/mnt/gpfs/seb/Database/CARD/CARD_DB.dmnd]
    blast: [blastp]
    annotation: [/mnt/gpfs/seb/Database/Kihyun_Lee_Databases/CARD_Annotation_V2.tsv]
    # min_Bitscore , max_Evalue , min_Pid , min_subject_pid , min_coverage , min_Query_coverage
    filter: [0,1e-5,0.8,0,0.2,0.8]
    color: "#00ff00"
  IntI:
    db: [/mnt/gpfs/seb/Database/Kihyun_Lee_Databases/IntI.db.dmnd]
    blast: [blastp]
    annotation: [none]
    # min_Bitscore , max_Evalue , min_Pid , min_subject_pid , min_coverage , min_Query_coverage
    filter: [0,1e-5,0.8,0,0.2,0.8]
    color: "#ff0000" 
cog_database: /home/sebr/seb/Database/rpsblast_cog_db/Cog
# ------ Binning parameters------ 
binning :
  concoct :
    contig_size : 1000
# ------ orf subgraph ------ 
graph :
  Card_int1: [CARD,IntI]
  Card: [CARD]
