# ------ Resssources ------ 
Percent_memory: 0.5 # maximum quantity of memory the snakemake can take
threads : 8 # single task nb threads
# ------ Path to data folder ------ 
data: ~/path/to/data/folder/ # path to data folder,   
# ------ Samples ------
# each sample need to have its own folder, with only 2 fastq files. Also, "fq.gz" are not detected. 
samples :
  setup : 1 
  file : /mnt/gpfs/seb/Project/temp/Anna/Assemblies/Samples.csv
  folder: /mnt/gpfs/seb/Project/temp/Anna/Data/
# ------ Assembly parameters ------
assembly: 
  assembler: megahit # only option so far, won't change in the near future
  parameters: --k-min 29 # additional parameters to be passed to megahit 
  per_sample: [folder_name|sample*] # a subfolder name where the anlysis is done | a regular expression to select which samples to runs  
  groups: 
      PerAD/AD7/AD7_1_11: # will create 3 directories PerAD/AD7/AD7_1_11, PerAD/AD1, AD2 : 
        ['AD7_W@(?([0-9])|1[0-1])?(_Repeat?)'] # you can put here any regular expression that ls can support. Here, it will mach with AD7_W1 to AD7_W11 ending or not with repeat 
      PerAD/AD1:  
        ["*"] 
      AD2:
        ["sample1"]
# ------ Binning parameters------ 
binning :
  concoct :
    contig_size : 1000 # min contig size considered
    execution : 1 # execution either 1 or 0 for yes or no
  metabat2 :
    contig_size : 1500 # min contig size considered
    execution : 1 # execution either 1 or 0 for yes or no
# ------ MAG anaysis------ 
maganalysis : 1 # execution either 1 or 0 for yes or no
# ------ DESMAN anaysis------ 
desman : 
  execution : 1 # execution either 1 or 0 for yes or no
  scripts : "~/seb/Applications/DESMAN/scripts"
  nb_haplotypes: 10
  nb_repeat: 5
  min_cov: 1
# ------ Annotation parameters ------ 
annotation: # support only diamond for now
  CARD:
    db: [/mnt/gpfs/seb/Database/CARD/CARD_DB_0.9.24.dmnd]
    blast: [blastp]
    # Annotation is a tsv file, 1st column is gene name, 2nd is new name (ex KO,COG), all others are optional/additional info (function, definition, pathway...)
    annotation: [/mnt/gpfs/seb/Database/Kihyun_Lee_Databases/CARD_Annotation_V2.tsv] 
    # min_Bitscore , max_Evalue , min_Pid , min_subject_pid , min_coverage , min_Query_coverage
    filter: [0,1e-5,0.8,0,0.2,0.8]
    color: "#00ff00" # orf graph
  IntI:
    db: [/mnt/gpfs/seb/Database/Kihyun_Lee_Databases/IntI.db.dmnd]
    blast: [blastp]
    # Annotation can be none, in this case, only gene name appears    
    annotation: [none] 
    # min_Bitscore , max_Evalue , min_Pid , min_subject_pid , min_coverage , min_Query_coverage
    filter: [0,1e-5,0.8,0,0.2,0.8]
    color: "#ff0000" # orf graph
cog_database: /home/sebr/seb/Database/rpsblast_cog_db/Cog
# ------ orf subgraph ------ 
graph :
  List_graphs:
    Card_int1: [CARD,IntI]
    Card: [CARD]
  CAT_database: /mnt/gpfs/seb/Database/NR_Cat
