# ------ Resssources ------ 
Percent_memory: 0.5 # maximum quantity of memory the snakemake can take
threads : 8 # single task nb threads
# ------ Path to data folder ------ 
data: /mnt/gpfs/seb/Project/Metahood/Test/Data  
# ------ Assembly parameters ------ 
assembly: 
  assembler: megahit
  parameters: --k-min 29 # additional parameters to be passed to megahit 
  per_sample: [sample*]
  groups: 
      PerAD/AD7/AD7_1_11: # will create 3 directories  
        ['AD7_W@(?([0-9])|1[0-1])?(_Repeat?)'] # you can put here any regular expression that ls can support. Here, it will mach with AD7_W1 to AD7_W11 ending or not with repeat 
      PerAD/AD1:  
        ["*"] 
      AD2:
        ["sample1"]
# ------ Annotation parameters ------ 
annotation:
  CARD:
    db: [/mnt/gpfs/seb/Database/CARD/CARD_DB_0.9.24.dmnd]
    blast: [blastp]
    annotation: [/mnt/gpfs/seb/Database/Kihyun_Lee_Databases/CARD_Annotation_V2.tsv]
    # min_Bitscore , max_Evalue , min_Pid , min_subject_pid , min_coverage , min_Query_coverage
    filter: [0,1e-5,0.8,0,0.2,0.8]
    color: "#00ff00"
  IntI:
    db: [/mnt/gpfs/seb/Database/Kihyun_Lee_Databases/IntI.db.dmnd]
    blast: [blastp]
    annotation: [none]
    # min_Bitscore , max_Evalue , min_Pid , min_subject_pid , min_coverage , min_Query_coverage
    filter: [0,1e-5,0.8,0,0.2,0.8]
    color: "#ff0000" 
cog_database: /home/sebr/seb/Database/rpsblast_cog_db/Cog
# ------ Binning parameters------ 
binning :
  concoct :
    contig_size : 1000
    execution : 1
  metabat2 :
    contig_size : 1500
    execution : 1
# ------ MAG anaysis------ 
Mag : [checkm,native] # value need to be checkm or native (NOT DONE YET, TODO)
  # ------ orf subgraph ------ 
graph :
  List_graphs:
    Card_int1: [CARD,IntI]
    Card: [CARD]
  CAT_database: /mnt/gpfs/seb/Database/NR_Cat
