FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="diamond" \
about.summary="diamond container for Metahood"

ENV diamond_version=2.0.6

ENV PACKAGES="curl g++ automake cmake zlib1g-dev"

RUN apt-get update \
&& apt-get install -y $PACKAGES \
&& curl -fsSL http://github.com/bbuchfink/diamond/archive/v${diamond_version}.tar.gz | tar -xz \
&& cd diamond-${diamond_version} \
&& mkdir build && cd build  \
&& cmake .. \
&& make && make install \
&& cd / && rm -r diamond-${diamond_version}
