FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="MultiQC" \
about.summary="MultiQC container for Metahood"

ENV multiqc_version=1.9 \ 
pandoc_version=2.3

ENV PACKAGES="make bzip2 curl gcc g++ libc6-dev libncurses-dev xz-utils zlib1g-dev libfreetype6 libpng-dev" \
PYTHON="python3 python3-dev python3-pip"

RUN apt-get update \
&& apt-get -y install $PACKAGES $PYTHON

WORKDIR /usr/local/bin
RUN curl -fsSL "https://github.com/jgm/pandoc/releases/download/${pandoc_version}/pandoc-${pandoc_version}-linux.tar.gz" | tar xz \
&& find /usr/local/bin/pandoc-${pandoc_version} -name "pandoc" -exec ln -s {} /usr/local/bin \;

RUN curl -fsSL "https://github.com/ewels/MultiQC/archive/v${multiqc_version}.tar.gz" | tar xz \
&& cd MultiQC-${multiqc_version} \
&& python3 setup.py install

