FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="bwa and samtools" \
about.summary="bwa and samtools container for Metahood"

ENV bwa_version=0.7.17 \
samtools_version=1.10 \
htslib_version=1.10 

ENV PACKAGES="curl g++ make zlib1g-dev libncurses-dev libbz2-dev liblzma-dev libcurl4-openssl-dev libfindbin-libs-perl"

RUN apt-get update \
&& apt-get install -y $PACKAGES \
&& curl -fsSL https://github.com/lh3/bwa/archive/v${bwa_version}.tar.gz | tar -C /usr/local/bin -xz \
&& make -C /usr/local/bin/bwa-${bwa_version} \
&& chmod +x /usr/local/bin/bwa-${bwa_version}/bwa \
&& curl -fsSL https://github.com/samtools/htslib/archive/${htslib_version}.tar.gz | tar xz \ 
&& curl -fsSL https://github.com/samtools/samtools/archive/${samtools_version}.tar.gz | tar xz \
&& make -C samtools-${samtools_version}  -j HTSDIR=../htslib-${htslib_version} \
&& make -C samtools-${samtools_version} -j HTSDIR=../htslib-${htslib_version} prefix=/usr/local install

ENV PATH ${PATH}:/usr/local/bin/bwa-${bwa_version}
