FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="python3" \
about.summary="python3 container for Metahood"

ENV PACKAGES="python3 python3-dev python3-pip bc" \
PYTHON_PACKAGES="ete3 biopython scipy numpy pyyaml"

RUN apt-get update \ 
&& apt-get install -y $PACKAGES \
&& ln -s /usr/bin/python3 /usr/bin/python \
&& pip3 --no-cache-dir install $PYTHON_PACKAGES
