FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="kofamscan" \
about.summary="kofamscan container for Metahood"

ENV kofamscan_version=1.3.0 \
ruby_version=2.6.6 \
hmmer_version=3.3.2

ENV PACKAGES="curl make cmake parallel"

RUN apt-get update \
&& apt-get -y install $PACKAGES \
&& curl -fsSL ftp://ftp.genome.jp/pub/tools/kofam_scan/kofam_scan-${kofamscan_version}.tar.gz | tar -xz \
&& cp -r kofam_scan-${kofamscan_version}/* /usr/local/bin \
&& rm -rf kofam_scan-${kofamscan_version} \
&& curl -fsSL http://eddylab.org/software/hmmer/hmmer-${hmmer_version}.tar.gz | tar -xz \
&& cd hmmer-${hmmer_version} \
&& ./configure \
&& make \
&& make install \
&& cd .. \
&& rm -rf hmmer-${hmmer_version} \
&& curl -fsSL https://cache.ruby-lang.org/pub/ruby/2.6/ruby-${ruby_version}.tar.gz | tar -xz \
&& cd ruby-${ruby_version} \
&& ./configure \
&& make \
&& make install \
&& cd .. \
&& rm -rf ruby-${ruby_version}
