FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="trim_galore" \
about.summary="Trim_galore container for Metahood"

ENV fastqc_version=0.11.9 \
trimgalore_version=0.6.5

ENV PACKAGES="curl openjdk-11-jre-headless python3 python3-cutadapt cutadapt unzip libfindbin-libs-perl pigz"

RUN apt-get update \
&& apt-get install -y $PACKAGES

RUN curl -fsSL "https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v${fastqc_version}.zip" \
&& unzip fastqc_v${fastqc_version}.zip \
&& chmod +x FastQC/fastqc \
&& mv FastQC /usr/local/bin \
&& rm -r fastqc*

ENV PATH ${PATH}:/usr/local/bin/FastQC/

RUN curl -fsSL "https://github.com/FelixKrueger/TrimGalore/archive/${trimgalore_version}.tar.gz" | tar xz \
&& mv TrimGalore-${trimgalore_version}/trim_galore /usr/local/bin \
&& rm -r TrimGalore*

