FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="FastQC" \
about.summary="FastQC container for Metahood"

ENV fastqc_version=0.11.9

ENV PACKAGES="curl unzip libfindbin-libs-perl openjdk-11-jre-headless"

RUN apt-get update \
&& apt-get install -y $PACKAGES \
&& curl -fsSL "http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v${fastqc_version}.zip" -o fastqc_v${fastqc_version}.zip \
&& unzip fastqc_v${fastqc_version}.zip \
&& chmod +x FastQC/fastqc \
&& mv FastQC /usr/local/bin \
&& rm *.zip

ENV PATH ${PATH}:/usr/local/bin/FastQC

